path:
  raw_data_path: './data/raw/nyc_taxi_data.csv'
  model_path: './models/taxi_duration_model.joblib'
  data_url: 'https://github.com/eishkina-estia/ML2023/raw/main/data/New_York_City_Taxi_Trip_Duration.zip'
  db_path: './data/processed/nyc_taxi_data.db'

value:
  random_state: 42
  test_size: 0.2
  target: 'trip_duration'
  features:
    - vendor_id
    - pickup_datetime
    - dropoff_datetime
    - passenger_count
    - pickup_longitude
    - pickup_latitude
    - dropoff_longitude
    - dropoff_latitude
    - store_and_fwd_flag